[phases.setup]
nixPkgs = [
  "nodejs_18",
  "yarn",
  "ruby_3_2"
]

[phases.build]
cmds = [
  "bundle install",
  "yarn install",
  "bundle exec rake assets:precompile"
]

[start]
cmd = "bundle exec rails server -b 0.0.0.0 -p $PORT"
